#!/usr/bin/env python3
# Autogenerated by https://github.com/BarnabyShearer/meta
"""Sphinx config."""

extensions = ["sphinxcontrib.autoprogram", "sphinx.ext.autodoc"]

project = "Ergonomic utilities for the terraform CLI."
copyright = "2021, Barnaby Shearer"
author = "Barnaby Shearer"

master_doc = "index"
